import localFont from "next/font/local";
import "../../app/globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <section className="">
      <div className="bg-bg1 bg-cover h-screen bg-black/50 bg-blend-overlay ">
        {children}
      </div>
    </section>
  );
}
