import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between px-12 bg-red-600 h-16 items-center">
          <h2>Title</h2>
          <ul className="flex flex-row justify-evenly w-1/4">
            <li>
              <Link href="/">Dashboard</Link>
            </li>
            <li>
              <Link href="/HeroBattle">Hero vs Hero</Link>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
