import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-between px-12 bg-red-600 h-20 items-center">
          <h2 className="text-5xl">Marvel Showdown</h2>
          <ul className="flex flex-row justify-evenly w-1/4">
            <li className="text-3xl hover:text-yellow-400">
              <Link href="/">Dashboard</Link>
            </li>
            <li className="text-3xl hover:text-yellow-400">
              <Link href="/HeroBattle">Hero vs Hero</Link>
            </li>
          </ul>
        </div>
        <div className="bg-bg2 bg-cover h-screen bg-black/50 bg-blend-overlay ">
          {children}
        </div>
      </body>
    </html>
  );
}
